version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/" # Location of your Gemfile
    schedule:
      interval: "weekly" # Check for updates weekly
    commit-message:
      prefix: "fix" # Commit message prefix

  - package-ecosystem: "npm"
    directory: "/" # Location of your package.json
    schedule:
      interval: "weekly" # Check for updates weekly
    commit-message:
      prefix: "fix"
