# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
permalink:        /recipes/:title

# Setup
title:            Jain Recipes
tagline:          'A Compilation of Jain Recipes'
description:      'Developed by Rishabh and Rahul Jain, JainRecipes.github.io features some of their favorite food recipes inspired by their grandma! '
url:              "https://jainrecipes.github.io/"
baseurl:          "https://jainrecipes.github.io/"

author:
  name:           'Rishabh and Rahul Jain'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/JainRecipes/JainRecipes.github.io
